{% set name = "octomap" %}
{% set version = "1.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OctoMap/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 417af6da4e855e9a83b93458aa98b01a2c88f880088baad2b59d323ce162586e
  patches:
    - 001-fix-exported-targets.patch  # [win]

build:
  number: 0
  run_exports:
    # Only static libraries are built on Windows
    - {{ pin_subpackage(name, max_pin='x.x') }}  # [not win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --libs {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
    - if exist %LIBRARY_PREFIX%\lib\octomap.lib (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/OctoMap/octomap
  license: BSD-3-Clause
  license_family: BSD
  license_file: octomap/LICENSE.txt
  summary: An Efficient Probabilistic 3D Mapping Framework Based on Octrees
  dev_url: https://github.com/OctoMap/octomap

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
