{% set name = "octomap" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OctoMap/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8da2576ec6a0993e8900db7f91083be8682d8397a7be0752c85d1b7dd1b8e992
  patches:
    - 001-fix-exported-targets.patch
    - 002-fix-isnan.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --libs {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
    - if exist %LIBRARY_PREFIX%\lib\octomap.lib (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/OctoMap/octomap
  license: BSD-3-Clause
  license_family: BSD
  license_file: octomap/LICENSE.txt
  summary: An Efficient Probabilistic 3D Mapping Framework Based on Octrees
  dev_url: https://github.com/OctoMap/octomap

extra:
  recipe-maintainers:
    - jeongseok-meta
    - jcarpent
    - wolfv
