{% set name = "octomap" %}
{% set version = "1.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OctoMap/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0f88c1c024f0d29ab74c7fb9f6ebfdddc8be725087372c6c4d8878be95831eb6
  patches:
    # Compatibility with C++17
    - fix-exported-targets.patch  # [win]
    - cmake-fix-linkage.patch     # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    # Only static libraries are built on Windows
    - {{ pin_subpackage(name, max_pin='x.x') }}  # [not win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --libs {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]
    - if exist %LIBRARY_PREFIX%\lib\octomap.lib (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/OctoMap/octomap
  license: BSD-3-Clause
  license_family: BSD
  license_file: octomap/LICENSE.txt
  summary: An Efficient Probabilistic 3D Mapping Framework Based on Octrees
  dev_url: https://github.com/OctoMap/octomap

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
