schema_version: 1

context:
  name: octomap
  version: "1.10.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/OctoMap/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: b6b6c10c99ab15701dd105840e7d4cf18e226eb68714dd4bdfe049dede5cd489
  patches:
    - 001-fix-exported-targets.patch
    - 002-fix-isnan.patch

build:
  number: 1
  script:
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
  run_exports:
    - ${{ pin_subpackage("octomap", upper_bound="x.x") }}

tests:
  - files:
      recipe:
        - tests/
    requirements:
      run:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - pkg-config
    script:
      - pkg-config --modversion octomap
      - pkg-config --libs octomap
      - cmake -S tests -B tests/build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - cmake --build tests/build --config Release
      - ctest --test-dir tests/build --output-on-failure --build-config Release

about:
  homepage: https://github.com/OctoMap/octomap
  repository: https://github.com/OctoMap/octomap
  license: BSD-3-Clause
  license_family: BSD
  license_file: octomap/LICENSE.txt
  summary: An Efficient Probabilistic 3D Mapping Framework Based on Octrees

extra:
  feedstock-name: octomap
  recipe-maintainers:
    - jeongseok-meta
    - jcarpent
    - wolfv
